version: "3.9"
services:
  
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433"
    environment:
      SA_PASSWORD: "!MyStrongPassword"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1500M
      restart_policy:
        condition: always
    networks:
      - internal
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "ecommerce"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 400M
      restart_policy:
        condition: always
    networks:
      - internal

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
      restart_policy:
        condition: always
    networks:
      - internal
  
  account:
    image: account:latest
    build:
      context: .
      dockerfile: ./src/Services/Account/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  catalog:
    image: catalog:latest
    build:
      context: .
      dockerfile: ./src/Services/Catalog/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  identity:
    image: identity:latest
    build:
      context: .
      dockerfile: ./src/Services/Identity/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  order:
    image: order:latest
    build:
      context: .
      dockerfile: ./src/Services/Order/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  payment:
    image: payment:latest
    build:
      context: .
      dockerfile: ./src/Services/Payment/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  shoppingcart:
    image: shoppingcart:latest
    build:
      context: .
      dockerfile: ./src/Services/ShoppingCart/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  warehouse:
    image: warehouse:latest
    build:
      context: .
      dockerfile: ./src/Services/Warehouse/WorkerService/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Staging
    depends_on:
      mssql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  webapi:
    image: webapi:latest
    build:
      context: .
      dockerfile: ./src/Web/WebAPI/Dockerfile
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
      restart_policy:
        condition: always
  
  webapp:
    image: webapp:latest
    build:
      context: .
      dockerfile: ./src/Web/WebAPP/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
    depends_on:
      webapi:
        condition: service_started
    networks:
      - internal
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: always

  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      webapi:
        condition: service_started
      webapp:
        condition: service_started
    ports:
      - "8080:80"
      - "5000:5000"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 80M
      restart_policy:
        condition: always

networks:
  internal:
    name: internal
    driver: bridge