name: _Quality
on:
  workflow_call:
    inputs:
      path:
        description: 'The path of project passed from the caller workflow'
        required: true
        type: string

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2

      - name: Cache dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget 
            
      - name: Run Analysis
        uses: codacy/codacy-analysis-cli-action@v4.2.0
        with:
          directory: ${{ inputs.path }}
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          tool: sonarscharp
          gh-code-scanning-compat: true
          #max-allowed-issues: 10
          #fail-if-incomplete: false

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: results.sarif
