name: _Security
on:
  workflow_call:
    inputs:
      path:
        description: 'The path of project passed from the caller workflow'
        required: true
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true
      matrix:
        language: [ csharp ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2

      - name: Cache dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget  

      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.1.28
        with:
          languages: ${{ matrix.language }}
          source-root: ${{ inputs.path }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2.1.28
        with:
          working-directory: ${{ inputs.path }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2.1.28
        with:
          checkout_path: ${{ inputs.path }}
